import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ee_web_archive, EEWebArchiveWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: EEWebArchive.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Local ArchivEE database config
# Currently using the original SQLite files, will be moved to Postgres later
config :ee_web_archive, EEWebArchive.ArchivEERepo,
  database: "/var/lib/ee-web-archive/ArchivEE.sqlite3",
  load_extensions: ["/var/lib/ee-web-archive/libsqlite_zstd.so"]
config :ee_web_archive, EEWebArchive.SmileyRepo, database: "/var/lib/ee-web-archive/smiley.sqlite3"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
